---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudnative-pg-cluster-admin
  namespace: adgangskomponent
spec:
  encryptedData:
    password: <MUST_REGEN>
    username: <MUST_REGEN>
  template:
    metadata:
      creationTimestamp: null
      name: cloudnative-pg-cluster-admin
      namespace: adgangskomponent
    type: Opaque
