apiVersion: v2
name: adgangskomponent
version: 0.0.0
dependencies:
  - name: cluster
    alias: cloudnative-pg
    version: 0.3.1
    repository: https://cloudnative-pg.github.io/charts
  - name: adgangskomponent
    version: 0.1.0
    repository: oci://ghcr.io/os2ai/adgangskomponent
