apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-resources
spec:
  destinations:
  - name: in-cluster
    namespace: kube-system
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: storage.k8s.io
    kind: StorageClass
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  orphanedResources:
    warn: false
  sourceRepos:
  - {{ .Values.repoUrl }} # git repository
