---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: search-agent-secrets
  namespace: search-agent
spec:
  encryptedData:
    SEARCH_AGENT_LLM_API_KEY: AgAXhEjapZnuh6WOgE8uSntHlA8OJ6zbiviwsZPz5/gRDpIQFJNxy6wjbX7sVr2GaFjNKLuUTz9aTXaRqDH633w2Y0uy0gk6OPbMmh5efqMdaZknzpnvq0S//gs4pHih7JtH1pGdrJbrNqMB08xg2kKo1VFMllXKIJ8jmN9GO6MRx5kqCsoigkqbjRl7+7Ypk5gVt0GMJbs56Xn5dYuf1dwYFB6XWCMPHBklGe2UjhvpZ11A0ZYR9/UKFkFEmYDZflayrvQPIaCJaaUdvfnf1c3UCiuLKuozAjMiw13jhOSTHTzDl/Bt/rZH90+sf75fRG9V6DRA0vtuxPVdGQto1FQQYhViHJLVz0jiBjmhi89m+CrYb2PRNqX4B2+Rd0evHilOl50qGoGpynYcjAypZ3aRdWiMPiUMTCcXcghZjO2ePCHXdEfZcxr6xdzaDPkDfvSPSYVJvjS/L5+FzHf//ycKxIRAM6K1HotDMB+uiIIOfayOtgL5neQkWoV0R8NUc7TgKRwnk9IyYTohj1FjV6WwUU/bYfeR5XBAWepuscS1o7LnCC2EAcyK2J989yIyGwu4G3QgqD/wESlL9cANdyc7fhX692oxXT/SgtCRlez6Emh3lG8fUywm4CR7fjXwrH2M1ZCbrDg+8WNsLhtd8l/zL2qD87jUlvd/Gt9yeOYkBGn5ibp5Bv7hXExi2v9inrw3IcTHjfFjnPhlRLCflFYXgtUoJDRW8bs+
  template:
    metadata:
      creationTimestamp: null
      name: search-agent-secrets
      namespace: search-agent
    type: Opaque
